# This is the configuration used to check the rubocop source code.

Rails:
  Enabled: true

AllCops:
  Exclude:
    - config/**/*
    - bin/**/*
    - node_modules/**/*
    - Gemfile
    - db/**/*

Documentation:
  Enabled: false

LineLength:
  Max: 99

Metrics/BlockLength:
  Exclude:
    - spec/**/*

HasAndBelongsToMany:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false