default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['user_name'] %>
  password: <%= ENV['password'] %>

development:
  <<: *default
  database: DTechnologies_api_development

test:
  <<: *default
  database: DTechnologies_api_test

production:
  <<: *default
  database: DTechnologies_api_production
